import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import { Montserrat } from "next/font/google";

const nunito = Nunito({
  variable: "--font-Nunito-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const montserrat = Montserrat({
  variable: "--font-Montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
});


export const metadata: Metadata = {
  title: "My app ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
